### ISSUE TITLE
Set Min required core version to 4.10.14.xxx

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-square-gateway#13]
As this payment method required changes within EE4 core for it to function, please set the min core version that this add-on can work with within the add-on.

Looking here: https://github.com/eventespresso/event-espresso-core/pull/3500

It looks like the min core version is `4.10.14.rc.001`

**Comment by lorenzocaum** [comment]
We updated the min core version this through this pull request:

https://github.com/eventespresso/eea-square-gateway/pull/14
