### ISSUE TITLE
Apple pay domain registration doesn't appear to work?

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-square-gateway#18]
Had reports from a couple of users that Apple pay domain validation isn't working so I tested it myself and can confirm the same issue.

Connect up your Square account and enable digital wallets in the Square payment method.

You then need to validate your domain with Square.

The links in the current payment method don't link to anything useful, they should go to something like this:

https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay#step-2-register-your-sandbox-domain-with-apple

Add your domain and validate by copying the file to your server.

Then try to pay using Apple pay.

On my set I'm getting:

> PaymentMethodUnsupportedError: Method unsupported: Your website's domain is not registered for use with Apple Pay.
> See: https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay#production-configuration

Yet the domain I'm using was validated with the account:

https://monosnap.com/file/YqH57Pt831o6sNnGg6mDUumqyJMXiM

**Comment by lorenzocaum** [comment]
Hi @Pebblo! 

I noticed the screenshot has the sandbox selected here (https://monosnap.com/file/YqH57Pt831o6sNnGg6mDUumqyJMXiM).

However, the error from Square is pointing to a help doc for production mode.

Is your Square payment gateway connected in production/live mode or sandbox/debug/test mode?

**Comment by Pebblo** [comment]
@lorenzocaum Yeah I'm connected in sandbox mode, to a sandbox account.

The screenshot above shows my ee4.pebblo.co.uk domain registered in sandbox.

Here are the settings for that site's Square PM: https://monosnap.com/file/doJrcxhX5HogglAF960mtxcnEIeY9T

The user I've been working with is the user from this thread:

https://eventespresso.com/topic/apple-pay-does-not-work-in-square-payment/

His Square settings: https://monosnap.com/file/nTz9QcrtVmiC6rNvX5OAtQPFdPupac
(I blurred his domain, but yes, it matches his site)

His settings: https://monosnap.com/file/iwOXQ6rPA5UHBxu36iKJihMlQxrIgi

**Comment by Pebblo** [comment]
> In this case our integration has almost nothing to do with registering a domain with Apple.

But you still need to do it within Square right? At least the docs mention doing so.

For me, the new link for the web-payments API has exactly the same directions to validate the domain but the docs mention fields that don't exist.

It directs me to go here: https://monosnap.com/file/ZoeI0qVbJ239DEAVA8erYke5ERZFKV

When I click to Add Sandbox domain: https://monosnap.com/file/O8qFUDSUDLUdIGR4iuko87PJ3G3nK2

**Comment by knazart** [comment]
> But you still need to do it within Square right

Yes, correct. That has to be done is Square dashboard. 

Hmm, sorry, yeah, the steps in both docs are almost identical. It seemed to me that the last step was more detailed in the more recent documentation, specifically mentioning the file that has to be downloaded and put on the server to validate. All the detailed steps should be there, on Square's website, in the modal, when you click Add Domain.

Try adding a domain in the Production tab. I don't think I used the Sandbox Domain. I simply added the domain in the production tab and both payment method modes worked just fine.

**Comment by Pebblo** [comment]
Still using a sandbox account?

I tried adding the domain to the production tab, same issue.

The user reporting this issue has the domain in the production tab, same issue.

**Comment by knazart** [comment]
This is a bit odd seeing that error while being the domain validated. Client domains are being marked as Verified as well (i.e. the validation in Square dashboard goes as expected) ?

**Comment by Pebblo** [comment]
Yeah, all looks correct in Square.

With an iOS device, the Apple pay icon does show, but can't be clicked.

When I test on Windows with Chrome, I see the above error mentioned.

**Comment by knazart** [comment]
You will see an error like that or similar if you try to use Apple Pay in anything other than Safari. But Google Pay should still work. I was not able to find a method to validate if Apple Pay will be able to initialize before trying to instantiate it as a part of Digital Wallet.

> With an iOS device, the Apple pay icon does show, but can't be clicked.

And there are no errors there in this scenario ?

**Comment by knazart** [comment]
I did just check, and I was wrong, I used the Sandbox tab for all my verified domains.

**Comment by Pebblo** [comment]
> And there are no errors there in this scenario ?

Can't answer that one, I don't use apple :)

You can take a look at the event here: https://ee4.pebblo.co.uk/events/changing-ticket-assignments/

**Comment by knazart** [comment]
@Pebblo  can you please connect (OAuth) with Square on your website, so I can go and take a look at the checkout page.

**Comment by Pebblo** [comment]
@knazart ?? Unless I'm misunderstanding, it is already connected.

I've just gone through, deactivated a bunch of payment methods and changed the Square logo in use so it's easier to spot.

**Comment by knazart** [comment]
Amm, when I selected that event and hit checkout I saw a SPCO error message that Square is not connected (OAuthed). 🤔

**Comment by Pebblo** [comment]
Does the Square Payment method add a message to SPCO for oAuth? I couldn't find one?

I had Quickbooks enabled which wasn't connected, are you sure it wasn't that?

**Comment by knazart** [comment]
Works fine now. Apple Pay is there but there is some JS error when you click it. Looking.

**Comment by Pebblo** [comment]
kk, so I haven't changed anything within Square other than the image so I'm guessing the notice you saw was from Quickbooks, which has now been deactivated.

**Comment by lorenzocaum** [comment]
Hey, I looked back at the testing notes for Square and I think I found the issue.

We used a testing account with Square. That let us manually add domains like these: https://user-images.githubusercontent.com/1079138/123165113-ce0f3d00-d441-11eb-9496-f622af21fc5e.jpg

I thought that live/production mode sets up an app in a customer's Square account. However, I now believe it uses an app called Event Espresso Integration (https://share.getcloudapp.com/yAu0q2BL). That means that a customer cannot go through the domain verification for Apple.

I found this which seems like it could solve the problem:

https://developer.squareup.com/docs/payment-form/cookbook/apple-pay-register-domains#programmatically-register-multiple-domains

It appears to use a global verification file. Then you post some information to allow a domain to use Apple Pay. If I understand that correctly, then adding that file to EventEspresso.com plus a button that runs the command in the Square payment method would solve the issue.

In the mean time, could we add the file to EventEspresso.com and use Postman to manually run the command?

**Comment by knazart** [comment]
Square feedback:
>Thanks for reaching out. I reached out internally to our eng team. They noted that since EventEspresso is a payment plugin for Wordpress sites, they did believe each of your customers’ payment forms will be hosted under a different domain that then would need to be registered with Apple. Can you test this out and see if it resolves the issue?

**Comment by lorenzocaum** [comment]
Hi Nazar, can we try this out?

https://developer.squareup.com/docs/payment-form/cookbook/apple-pay-register-domains#programmatically-register-multiple-domains

Specifically, could we add the file to EventEspresso.com and use Postman to manually run the command?

This is my testing site that is connected to Square in live mode: https://enzo12staging.wpengine.com

If that works, then we could get the customer domains and use the manual process for each site with Postman. That will give us time to think of a way to let customers do this through the Square payment method.

**Comment by knazart** [comment]
Ok, you can try the ENH/add-domain-validation branch. You should see a "Register my domain" on the PM settings page. Need to be OAuthed for it to work.

**Comment by knazart** [comment]
> Thanks for following up. We do not think that having each customer create their own ‘app’ in the developer dashboard and validating the domain in their (the sellers) account is the correct workflow. Since the payment form is tokenizing cards using EventEspresso’s app_id, all of the domains need to be validated in EventEspresso’s Square account that owns this app. We think that EventEspresso needs to use our ApplePay API to register each new customer domain in EventEspresso’s app when that customer installs the plugin to register domains in a scalable fashion
