### ISSUE TITLE
Add PHP Version Check

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/eea-square-gateway#20]
For more info plz see: https://p2.eventespresso.com/2021/11/30/min-php-version-requirements-for-core-and-add-ons/

Need to add the following logic:

-  add a PHP version check prior to registration
- set min PHP version 7.1 ( `PHP_VERSION_ID` :  `70100` )
- if PHP version is not met:
	- deactivate add-on
	- display error notice

The following can be used as a rough guide: 
https://github.com/eventespresso/eea-recurring-events-manager/blob/master/eea-recurring-events-manager.php

**Comment by Pebblo** [comment]
@knazart can you add this so I can include it in the next release? 

I'm trying to reduce the number of issues from the Square payment method.

----

Note - the Braintree payment method also does this, although it doesn't de-activate the add-on itself it 'disables' the payment method and shows a notice in the admin.

PHP7.2+ : https://monosnap.com/file/7hU3n2hlxE0D9V9yXvPwFgDoi5qvV3

PHP7.1 and below: https://monosnap.com/file/AXUkaTHcC70DYkX3uMnhbNgTKCp6eg
