### ISSUE TITLE
Release Square

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-square-gateway#7]
https://trello.com/c/NCaKHCN3/

**Comment by lorenzocaum** [comment]
Hi @nazar, I'm starting on the launch for Square. We have a checklist for different parts that I'm following.

There are a few things that I need help with:

>Double-check naming standards: Event Espresso - Name of Plugin (Minimum EE4 version) / for example Event Espresso - Authorize.net AIM eCheck Gateway (EE 4.8.41+); repository should also start with "eea-"; remove unnecessary files from repository (e.g. boilerplate code)

>Set up through Grunt: https://github.com/eventespresso/ee-and-es-docs/blob/master/server-administration/how-tos/grunt-and-automation/adding-a-plugin-to-grunt-buildmachine.md

>A release build as a zip.

**Comment by lorenzocaum** [comment]
**Pre-launch notes**

Introduction about plugin.

**GitHub slug**: eea-square-gateway

**Recurly plan code**: eea_square_gateway+yearly
**Product page slug**: eea-square-gateway
**Documentation page slug**: eea-square-gateway

**Recurly Event Espresso live:** https://eventespresso.recurly.com/plans/???+yearly
**Recurly Event Espresso staging:** https://stagingeecom.recurly.com/plans/???+yearly

**PUE library**: https://eventespresso.com/wp-admin/admin.php?page=plugin_update_page

**Event Espresso live product page**: 
- https://docs.google.com/document/d/1K4mUStQfny_IvWSFWwKN1fR2phl60IgJFF1Ncs_wG-0/edit#heading=h.ftntm6z0f0xf 
- https://eventespresso.com/?post_type=pues2custom_pricing&p=300365&preview=true 
- https://eventespresso.com/product/???/

**Documentation page**: 
- https://docs.google.com/document/d/1vyLyLbhcc7IaGdw5gMDkMxnJW_SSdwLA8XD4JQd_tt4/edit 
- https://eventespresso.com/
- https://eventespresso.com/wiki/???/

**Trello card**: https://trello.com/c/NCaKHCN3/
**P2**:

**Comment by lorenzocaum** [comment]
@sethshoultes Can you please create a product image for Square?

Here is an example from Stripe:

![ee4-stripe-verified-logo-380x250](https://user-images.githubusercontent.com/1079138/140333263-46752e10-26a2-439a-ab48-9b6ad7993185.jpg)

**Comment by lorenzocaum** [comment]
Hi Nazar, can you help me with these items?

https://github.com/eventespresso/eea-square-gateway/issues/7#issuecomment-958105137

**Comment by knazart** [comment]
Hi Lorenzo.
It's on my radar from day one when you created this issue. Sorry for postponing, but had to finish up one of my tasks.. Now I'm looking into this to make sure that there are no debug code etc. Doesn't look like there is. Looks clean.
I also started on the unit tests for this add-on and some work that I think should be in the release ready plugin is involved in those changes (that are still in the process). So I'm debating on committing the basis of unit tests to allow the release, and in parallel continue working on the unit tests.

Will try to leave feedback on the other items in the list as soon as I can.

**Comment by sethshoultes** [comment]
@lorenzocaum here you go:
https://www.canva.com/design/DAEu34aw-HY/AlbSqq8Xh_c3QO9luVKpZg/edit
![Square Payment Gateway](https://user-images.githubusercontent.com/235315/140533890-a72847f2-ba75-4c8f-acd8-05a44d9fbcd7.png)

I ended up creating this in Canva because I'm not sure how much longer I'll have access to Photoshop on a really old laptop. I exported the PSD template we use as an image, then imported it into Canva to add the logo and text. I think this will be more accessible in the long run.

**Comment by lorenzocaum** [comment]
@knazart Thanks for looking into the pre-launch tasks. I found an issue while writing documentation:

https://github.com/eventespresso/eea-square-gateway/issues/8

@sethshoultes Thanks for switching to Canva and sharing the product image. That will work better.

**Comment by knazart** [comment]
> Double-check naming standards

Done.

> Set up through Grunt

Done.

> A release build as a zip

Don't think I ever did that. I think Tony usually does that, no ?

**Comment by lorenzocaum** [comment]
@knazart Thank you for getting Square ready to go!

I saw there is an open pull request: https://github.com/eventespresso/eea-square-gateway/pull/12

I'll ask Tony about a release build after that is merged.

**Comment by lorenzocaum** [comment]
@Pebblo Can you please run a release build for Square? 

I'm not sure what information you need for that but the Github slug is:

eea-square-gateway

**Comment by lorenzocaum** [comment]
@Pebblo Can you please run a release build for Square? 

I'm not sure what information you need for that but the Github slug is:

eea-square-gateway

**Comment by lorenzocaum** [comment]
https://p2.eventespresso.com/2021/11/17/we-launched-the-square-payment-gateway-today-product/

https://trello.com/c/NCaKHCN3/742-launch-square-payment-gateway
