### ISSUE TITLE
Uncaught Error: Class 'EventEspresso\core\services\encryption\openssl\OpenSSLv2 in SquareOpenSSLEncryption.php:19

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-square-gateway#8]
**Master branch of Square** + Event Espresso 4.10.13.p

I'm writing the documentation for Square and I see the following after clicking the button to authorize:

```
Fatal error: Uncaught Error: Class 'EventEspresso\core\services\encryption\openssl\OpenSSLv2' not found in /nas/content/staging/enzo12/wp-content/plugins/eea-square-gateway-master/tools/encryption/SquareOpenSSLEncryption.php:19 Stack trace: #0 /nas/content/staging/enzo12/wp-content/plugins/event-espresso-core-reg/core/Psr4Autoloader.php(189): require() #1 /nas/content/staging/enzo12/wp-content/plugins/event-espresso-core-reg/core/Psr4Autoloader.php(170): EventEspresso\core\Psr4Autoloader->requireFile('/nas/content/st...') #2 /nas/content/staging/enzo12/wp-content/plugins/event-espresso-core-reg/core/Psr4Autoloader.php(138): EventEspresso\core\Psr4Autoloader->loadMappedFile('EventEspresso\\S...', 'tools\\encryptio...') #3 [internal function]: EventEspresso\core\Psr4Autoloader->loadClass('EventEspresso\\S...') #4 [internal function]: spl_autoload_call('EventEspresso\\S...') #5 /nas/content/staging/enzo12/wp-content/plugins/event-espresso-core-reg/core/services/loaders/ClassInterfaceCache.php(54): class_exists('EventEspresso in /nas/content/staging/enzo12/wp-content/plugins/eea-square-gateway-master/tools/encryption/SquareOpenSSLEncryption.php on line 19
```

**Steps to reproduce**

- Activate the current version of Event Espresso on a WordPress site.
- Add master version of Square.
- Go to Event Espresso --> Payment Methods and click on Square.
- Activate Square and then scroll down to the connect button.
- Click on the connect button and a small window will appear.
- Login and continue through the process to connect the account.
- Once you click the final button, then you'll see this:

![WordPress › Error 2021-11-05 at 11 28 31 AM](https://user-images.githubusercontent.com/1079138/140536117-6acbf697-430e-4dec-9cfc-52230413320e.jpg)

**Reported or seen on**

**Other notes**

**Comment by lorenzocaum** [comment]
I realized my testing site had the decaf constant enabled.

I turned that off and I still see the issue:

https://github.com/eventespresso/eea-square-gateway/issues/8#issue-1045975866

**Comment by knazart** [comment]
It's most likely a core issue. The latest master branch works just fine. Will need to do a core release.

**Comment by lorenzocaum** [comment]
Hi Nazar, you are correct. I switched to master and the connection worked. 

I'm finishing up the draft of the documentation page today.
